---
name: build java code

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    name: Build and Deploy extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: kharkevich
        minimum-approvals: 1
        issue-title: "Deploying prod from staging"
        exclude-workflow-initiator-as-approver: false

    - uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk 
        architecture: x64 
