name: Create Issue

on:
 workflow_dispatch:

jobs:
  plan:
    name: Running
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Propagate deployment to stg environment
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: "stg"
