name: Issue

on:
  issues:
    types: [opened]

jobs:
  plan:
    name: Running
    runs-on: ubuntu-latest
    steps:
        - name: name
          run: env
        - name: test2
          env:
            ISSUE: ${{ github.event.issue.number }}
          run: |
            echo "$ISSUE"
