name: Create Issue

on:
 workflow_dispatch:

jobs:
  plan:
    name: Running
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Propagate deployment to stg environment
        uses: JasonEtco/create-an-issue@v2
        id: create_issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: "stg"
    outputs:
      number: ${{ steps.create_issue.outputs.number }}
  run:
    name: run!
    needs: plan
    permissions:
      id-token: write # need this for OIDC
      contents: read
      issues: write
    uses: kharkevich/playground/.github/workflows/labeled.yml@master
    with:
      issue_id: ${{ needs.plan.outputs.number }}
    secrets: inherit
