name: Issue

on:
  issues:
    types: [opened]

jobs:
  plan:
    name: Running
    runs-on: ubuntu-latest
    steps:
        - name: name
          run: env
        - name: test2
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
            ISSUE: ${{ toJson(github.event.issue.number) }}
          run: |
            echo "$GITHUB_CONTEXT"
            echo "$ISSUE"
