name: test issue

on:
  issue_comment:
    types:
      - created

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test issue comment
        uses: kharkevich/playground-action@master
