name: test issue

on:
  issue_comment:
    types:
      - created

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    steps:
      - name: Test issue comment
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "test",
            });
