name: test issue

on:
  issue_comment:
    types:
      - created
permissions:
  contents: write
  pull-requests: write 
  issues: write

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test issue comment
        uses: kharkevich/playground-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          mode: list
          approvers: kharkevich
